### ISSUE TITLE
Fix catalog page not displaying

### ISSUE THREAD

**Issue by cjchiang** [payloaders/PoEEquips#33]
Catalog page cannot be seen? or found

**Comment by Castielketaimo** [comment]
Please ensure you have info/catalog since the controller is in info controller. Its tested fine on my local machine

**Comment by cjchiang** [comment]
Not the info/catalog but catalog itself

**Comment by Castielketaimo** [comment]
you mean the display format I believe, and that's in other issues catalog controller & view.

**Comment by cjchiang** [comment]
Closing this as it overlaps with other reopen issued for the setup of controller and view #8
