### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Castielketaimo** [payloaders/PoEEquips#58]
1.Add entity model for accessories (same as lab 7)
2.Test for valid attribute ranges and valid image name
	- inside of the model (valid when add into collection
3.Create entity model for set of gear (Only one accessory for a category)
	- Check add() or update()
	- write test case for this
4.Use Category code (L, R) instead of Left hand. Have functions takes in the code
	and validates it

**Comment by Qlam77** [comment]
you like giving me the most difficult ones

**Comment by Qlam77** [comment]
you really gave me the hardest one

**Comment by Qlam77** [comment]
MUH COMMENTS

**Comment by RonnoTran** [comment]
hello Quincy 👍

**Comment by Qlam77** [comment]
REBEL AGAINST THE ADMIN

**Comment by RonnoTran** [comment]
🗡

**Comment by cjchiang** [comment]
It's treason then 🗡 💀

**Comment by Qlam77** [comment]
h

**Comment by Qlam77** [comment]
e

**Comment by Qlam77** [comment]
l

**Comment by Qlam77** [comment]
p

**Comment by Qlam77** [comment]
💯

**Comment by RonnoTran** [comment]
( ͡° ͜ʖ ͡°)

**Comment by Qlam77** [comment]
![image](https://user-images.githubusercontent.com/22090866/38060407-71bccc44-329f-11e8-8b12-b6ac71a166f7.png)
